/*
Sellix Developers API

Testing CouponsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CouponsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CouponsAPIService CreateCoupon", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CouponsAPI.CreateCoupon(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CouponsAPIService DeleteCoupon", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uniqid string

		resp, httpRes, err := apiClient.CouponsAPI.DeleteCoupon(context.Background(), uniqid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CouponsAPIService GetCoupon", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uniqid string

		resp, httpRes, err := apiClient.CouponsAPI.GetCoupon(context.Background(), uniqid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CouponsAPIService ListCoupons", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CouponsAPI.ListCoupons(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CouponsAPIService UpdateCoupon", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var uniqid string

		resp, httpRes, err := apiClient.CouponsAPI.UpdateCoupon(context.Background(), uniqid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
