/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateProduct200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProduct200Response{}

// UpdateProduct200Response struct for UpdateProduct200Response
type UpdateProduct200Response struct {
	Status *int32 `json:"status,omitempty"`
	Data *UpdateProduct200ResponseData `json:"data,omitempty"`
	Error *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Env *string `json:"env,omitempty"`
	Log map[string]interface{} `json:"log,omitempty"`
}

// NewUpdateProduct200Response instantiates a new UpdateProduct200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProduct200Response() *UpdateProduct200Response {
	this := UpdateProduct200Response{}
	return &this
}

// NewUpdateProduct200ResponseWithDefaults instantiates a new UpdateProduct200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProduct200ResponseWithDefaults() *UpdateProduct200Response {
	this := UpdateProduct200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdateProduct200Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProduct200Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateProduct200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *UpdateProduct200Response) SetStatus(v int32) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateProduct200Response) GetData() UpdateProduct200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret UpdateProduct200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProduct200Response) GetDataOk() (*UpdateProduct200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateProduct200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given UpdateProduct200ResponseData and assigns it to the Data field.
func (o *UpdateProduct200Response) SetData(v UpdateProduct200ResponseData) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *UpdateProduct200Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProduct200Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *UpdateProduct200Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *UpdateProduct200Response) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *UpdateProduct200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProduct200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *UpdateProduct200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *UpdateProduct200Response) SetMessage(v string) {
	o.Message = &v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *UpdateProduct200Response) GetEnv() string {
	if o == nil || IsNil(o.Env) {
		var ret string
		return ret
	}
	return *o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProduct200Response) GetEnvOk() (*string, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *UpdateProduct200Response) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given string and assigns it to the Env field.
func (o *UpdateProduct200Response) SetEnv(v string) {
	o.Env = &v
}

// GetLog returns the Log field value if set, zero value otherwise.
func (o *UpdateProduct200Response) GetLog() map[string]interface{} {
	if o == nil || IsNil(o.Log) {
		var ret map[string]interface{}
		return ret
	}
	return o.Log
}

// GetLogOk returns a tuple with the Log field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProduct200Response) GetLogOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Log) {
		return map[string]interface{}{}, false
	}
	return o.Log, true
}

// HasLog returns a boolean if a field has been set.
func (o *UpdateProduct200Response) HasLog() bool {
	if o != nil && !IsNil(o.Log) {
		return true
	}

	return false
}

// SetLog gets a reference to the given map[string]interface{} and assigns it to the Log field.
func (o *UpdateProduct200Response) SetLog(v map[string]interface{}) {
	o.Log = v
}

func (o UpdateProduct200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProduct200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Log) {
		toSerialize["log"] = o.Log
	}
	return toSerialize, nil
}

type NullableUpdateProduct200Response struct {
	value *UpdateProduct200Response
	isSet bool
}

func (v NullableUpdateProduct200Response) Get() *UpdateProduct200Response {
	return v.value
}

func (v *NullableUpdateProduct200Response) Set(val *UpdateProduct200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProduct200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProduct200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProduct200Response(val *UpdateProduct200Response) *NullableUpdateProduct200Response {
	return &NullableUpdateProduct200Response{value: val, isSet: true}
}

func (v NullableUpdateProduct200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProduct200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


