/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetProduct200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProduct200ResponseData{}

// GetProduct200ResponseData struct for GetProduct200ResponseData
type GetProduct200ResponseData struct {
	Product *Product `json:"product,omitempty"`
}

// NewGetProduct200ResponseData instantiates a new GetProduct200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProduct200ResponseData() *GetProduct200ResponseData {
	this := GetProduct200ResponseData{}
	return &this
}

// NewGetProduct200ResponseDataWithDefaults instantiates a new GetProduct200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProduct200ResponseDataWithDefaults() *GetProduct200ResponseData {
	this := GetProduct200ResponseData{}
	return &this
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *GetProduct200ResponseData) GetProduct() Product {
	if o == nil || IsNil(o.Product) {
		var ret Product
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProduct200ResponseData) GetProductOk() (*Product, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *GetProduct200ResponseData) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given Product and assigns it to the Product field.
func (o *GetProduct200ResponseData) SetProduct(v Product) {
	o.Product = &v
}

func (o GetProduct200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProduct200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	return toSerialize, nil
}

type NullableGetProduct200ResponseData struct {
	value *GetProduct200ResponseData
	isSet bool
}

func (v NullableGetProduct200ResponseData) Get() *GetProduct200ResponseData {
	return v.value
}

func (v *NullableGetProduct200ResponseData) Set(val *GetProduct200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProduct200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProduct200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProduct200ResponseData(val *GetProduct200ResponseData) *NullableGetProduct200ResponseData {
	return &NullableGetProduct200ResponseData{value: val, isSet: true}
}

func (v NullableGetProduct200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProduct200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


