/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sellix

import (
	"encoding/json"
)

// checks if the GetSubscriptionv2200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubscriptionv2200ResponseData{}

// GetSubscriptionv2200ResponseData struct for GetSubscriptionv2200ResponseData
type GetSubscriptionv2200ResponseData struct {
	Subscription *ProductSubscription `json:"subscription,omitempty"`
}

// NewGetSubscriptionv2200ResponseData instantiates a new GetSubscriptionv2200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSubscriptionv2200ResponseData() *GetSubscriptionv2200ResponseData {
	this := GetSubscriptionv2200ResponseData{}
	return &this
}

// NewGetSubscriptionv2200ResponseDataWithDefaults instantiates a new GetSubscriptionv2200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSubscriptionv2200ResponseDataWithDefaults() *GetSubscriptionv2200ResponseData {
	this := GetSubscriptionv2200ResponseData{}
	return &this
}

// GetSubscription returns the Subscription field value if set, zero value otherwise.
func (o *GetSubscriptionv2200ResponseData) GetSubscription() ProductSubscription {
	if o == nil || IsNil(o.Subscription) {
		var ret ProductSubscription
		return ret
	}
	return *o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSubscriptionv2200ResponseData) GetSubscriptionOk() (*ProductSubscription, bool) {
	if o == nil || IsNil(o.Subscription) {
		return nil, false
	}
	return o.Subscription, true
}

// HasSubscription returns a boolean if a field has been set.
func (o *GetSubscriptionv2200ResponseData) HasSubscription() bool {
	if o != nil && !IsNil(o.Subscription) {
		return true
	}

	return false
}

// SetSubscription gets a reference to the given ProductSubscription and assigns it to the Subscription field.
func (o *GetSubscriptionv2200ResponseData) SetSubscription(v ProductSubscription) {
	o.Subscription = &v
}

func (o GetSubscriptionv2200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubscriptionv2200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subscription) {
		toSerialize["subscription"] = o.Subscription
	}
	return toSerialize, nil
}

type NullableGetSubscriptionv2200ResponseData struct {
	value *GetSubscriptionv2200ResponseData
	isSet bool
}

func (v NullableGetSubscriptionv2200ResponseData) Get() *GetSubscriptionv2200ResponseData {
	return v.value
}

func (v *NullableGetSubscriptionv2200ResponseData) Set(val *GetSubscriptionv2200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubscriptionv2200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubscriptionv2200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubscriptionv2200ResponseData(val *GetSubscriptionv2200ResponseData) *NullableGetSubscriptionv2200ResponseData {
	return &NullableGetSubscriptionv2200ResponseData{value: val, isSet: true}
}

func (v NullableGetSubscriptionv2200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubscriptionv2200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


