/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sellix

import (
	"encoding/json"
)

// checks if the SubscriptionTrialResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionTrialResponse{}

// SubscriptionTrialResponse struct for SubscriptionTrialResponse
type SubscriptionTrialResponse struct {
	Status *int32 `json:"status,omitempty"`
	Data *SubscriptionTrialResponseData `json:"data,omitempty"`
	Error *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Env *string `json:"env,omitempty"`
	Log map[string]interface{} `json:"log,omitempty"`
}

// NewSubscriptionTrialResponse instantiates a new SubscriptionTrialResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionTrialResponse() *SubscriptionTrialResponse {
	this := SubscriptionTrialResponse{}
	return &this
}

// NewSubscriptionTrialResponseWithDefaults instantiates a new SubscriptionTrialResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionTrialResponseWithDefaults() *SubscriptionTrialResponse {
	this := SubscriptionTrialResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *SubscriptionTrialResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionTrialResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *SubscriptionTrialResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *SubscriptionTrialResponse) SetStatus(v int32) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SubscriptionTrialResponse) GetData() SubscriptionTrialResponseData {
	if o == nil || IsNil(o.Data) {
		var ret SubscriptionTrialResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionTrialResponse) GetDataOk() (*SubscriptionTrialResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SubscriptionTrialResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given SubscriptionTrialResponseData and assigns it to the Data field.
func (o *SubscriptionTrialResponse) SetData(v SubscriptionTrialResponseData) {
	o.Data = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SubscriptionTrialResponse) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionTrialResponse) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SubscriptionTrialResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *SubscriptionTrialResponse) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SubscriptionTrialResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionTrialResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SubscriptionTrialResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SubscriptionTrialResponse) SetMessage(v string) {
	o.Message = &v
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *SubscriptionTrialResponse) GetEnv() string {
	if o == nil || IsNil(o.Env) {
		var ret string
		return ret
	}
	return *o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionTrialResponse) GetEnvOk() (*string, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *SubscriptionTrialResponse) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given string and assigns it to the Env field.
func (o *SubscriptionTrialResponse) SetEnv(v string) {
	o.Env = &v
}

// GetLog returns the Log field value if set, zero value otherwise.
func (o *SubscriptionTrialResponse) GetLog() map[string]interface{} {
	if o == nil || IsNil(o.Log) {
		var ret map[string]interface{}
		return ret
	}
	return o.Log
}

// GetLogOk returns a tuple with the Log field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionTrialResponse) GetLogOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Log) {
		return map[string]interface{}{}, false
	}
	return o.Log, true
}

// HasLog returns a boolean if a field has been set.
func (o *SubscriptionTrialResponse) HasLog() bool {
	if o != nil && !IsNil(o.Log) {
		return true
	}

	return false
}

// SetLog gets a reference to the given map[string]interface{} and assigns it to the Log field.
func (o *SubscriptionTrialResponse) SetLog(v map[string]interface{}) {
	o.Log = v
}

func (o SubscriptionTrialResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionTrialResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.Log) {
		toSerialize["log"] = o.Log
	}
	return toSerialize, nil
}

type NullableSubscriptionTrialResponse struct {
	value *SubscriptionTrialResponse
	isSet bool
}

func (v NullableSubscriptionTrialResponse) Get() *SubscriptionTrialResponse {
	return v.value
}

func (v *NullableSubscriptionTrialResponse) Set(val *SubscriptionTrialResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionTrialResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionTrialResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionTrialResponse(val *SubscriptionTrialResponse) *NullableSubscriptionTrialResponse {
	return &NullableSubscriptionTrialResponse{value: val, isSet: true}
}

func (v NullableSubscriptionTrialResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionTrialResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


