/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sellix

import (
	"encoding/json"
)

// checks if the Feedback type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Feedback{}

// Feedback struct for Feedback
type Feedback struct {
	// Unique ID of the resource, used as reference across the API.
	Uniqid *string `json:"uniqid,omitempty"`
	// Unique ID of the product for which this feedback has been posted.
	ProductId *string `json:"product_id,omitempty"`
	// Unique ID of the invoice for which this feedback has been posted.
	InvoiceId *string `json:"invoice_id,omitempty"`
	// If true, this feedback has been blocked after an appeal.
	Blocked *bool `json:"blocked,omitempty"`
	// If true, an appeal has been created for this feedback.
	Appealed *bool `json:"appealed,omitempty"`
	// The shop ID to which this feedback belongs.
	ShopId *int32 `json:"shop_id,omitempty"`
	// Message left by the customer.
	Message *string `json:"message,omitempty"`
	// Reply left by the merchant.
	Reply *string `json:"reply,omitempty"`
	// Score left by the customer, if 0 no score has been left.
	Score *int32 `json:"score,omitempty"`
	// Timestamp for the creation of the feedback.
	CreatedAt *int32 `json:"created_at,omitempty"`
	// Date, available if the product has been edited.
	UpdatedAt *int32 `json:"updated_at,omitempty"`
	// Product title for which this feedback has been created
	ProductTitle *string `json:"product_title,omitempty"`
	// Unique id of the image attachment for this product with the image extension included.
	ProductImageName *string `json:"product_image_name,omitempty"`
	// Where the image is stored in our self-hosted CDN.
	ProductImageStorage *string `json:"product_image_storage,omitempty"`
	// The cloudflare image ID of this product, replaces image_attachment and image_name. Format https://imagedelivery.net/95QNzrEeP7RU5l5WdbyrKw/<cloudflare_image_id>/<variant_name> where variant_name can be shopItem, avatar, icon, imageAvatarFeedback, public, productImageCart.
	CloudflareImageId *string `json:"cloudflare_image_id,omitempty"`
	Invoice *MiniInvoice `json:"invoice,omitempty"`
	Product *FeedbackProduct `json:"product,omitempty"`
	// User ID of the user who updated the feedback.
	UpdatedBy *int32 `json:"updated_by,omitempty"`
}

// NewFeedback instantiates a new Feedback object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeedback() *Feedback {
	this := Feedback{}
	return &this
}

// NewFeedbackWithDefaults instantiates a new Feedback object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeedbackWithDefaults() *Feedback {
	this := Feedback{}
	return &this
}

// GetUniqid returns the Uniqid field value if set, zero value otherwise.
func (o *Feedback) GetUniqid() string {
	if o == nil || IsNil(o.Uniqid) {
		var ret string
		return ret
	}
	return *o.Uniqid
}

// GetUniqidOk returns a tuple with the Uniqid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetUniqidOk() (*string, bool) {
	if o == nil || IsNil(o.Uniqid) {
		return nil, false
	}
	return o.Uniqid, true
}

// HasUniqid returns a boolean if a field has been set.
func (o *Feedback) HasUniqid() bool {
	if o != nil && !IsNil(o.Uniqid) {
		return true
	}

	return false
}

// SetUniqid gets a reference to the given string and assigns it to the Uniqid field.
func (o *Feedback) SetUniqid(v string) {
	o.Uniqid = &v
}

// GetProductId returns the ProductId field value if set, zero value otherwise.
func (o *Feedback) GetProductId() string {
	if o == nil || IsNil(o.ProductId) {
		var ret string
		return ret
	}
	return *o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetProductIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProductId) {
		return nil, false
	}
	return o.ProductId, true
}

// HasProductId returns a boolean if a field has been set.
func (o *Feedback) HasProductId() bool {
	if o != nil && !IsNil(o.ProductId) {
		return true
	}

	return false
}

// SetProductId gets a reference to the given string and assigns it to the ProductId field.
func (o *Feedback) SetProductId(v string) {
	o.ProductId = &v
}

// GetInvoiceId returns the InvoiceId field value if set, zero value otherwise.
func (o *Feedback) GetInvoiceId() string {
	if o == nil || IsNil(o.InvoiceId) {
		var ret string
		return ret
	}
	return *o.InvoiceId
}

// GetInvoiceIdOk returns a tuple with the InvoiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetInvoiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InvoiceId) {
		return nil, false
	}
	return o.InvoiceId, true
}

// HasInvoiceId returns a boolean if a field has been set.
func (o *Feedback) HasInvoiceId() bool {
	if o != nil && !IsNil(o.InvoiceId) {
		return true
	}

	return false
}

// SetInvoiceId gets a reference to the given string and assigns it to the InvoiceId field.
func (o *Feedback) SetInvoiceId(v string) {
	o.InvoiceId = &v
}

// GetBlocked returns the Blocked field value if set, zero value otherwise.
func (o *Feedback) GetBlocked() bool {
	if o == nil || IsNil(o.Blocked) {
		var ret bool
		return ret
	}
	return *o.Blocked
}

// GetBlockedOk returns a tuple with the Blocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetBlockedOk() (*bool, bool) {
	if o == nil || IsNil(o.Blocked) {
		return nil, false
	}
	return o.Blocked, true
}

// HasBlocked returns a boolean if a field has been set.
func (o *Feedback) HasBlocked() bool {
	if o != nil && !IsNil(o.Blocked) {
		return true
	}

	return false
}

// SetBlocked gets a reference to the given bool and assigns it to the Blocked field.
func (o *Feedback) SetBlocked(v bool) {
	o.Blocked = &v
}

// GetAppealed returns the Appealed field value if set, zero value otherwise.
func (o *Feedback) GetAppealed() bool {
	if o == nil || IsNil(o.Appealed) {
		var ret bool
		return ret
	}
	return *o.Appealed
}

// GetAppealedOk returns a tuple with the Appealed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetAppealedOk() (*bool, bool) {
	if o == nil || IsNil(o.Appealed) {
		return nil, false
	}
	return o.Appealed, true
}

// HasAppealed returns a boolean if a field has been set.
func (o *Feedback) HasAppealed() bool {
	if o != nil && !IsNil(o.Appealed) {
		return true
	}

	return false
}

// SetAppealed gets a reference to the given bool and assigns it to the Appealed field.
func (o *Feedback) SetAppealed(v bool) {
	o.Appealed = &v
}

// GetShopId returns the ShopId field value if set, zero value otherwise.
func (o *Feedback) GetShopId() int32 {
	if o == nil || IsNil(o.ShopId) {
		var ret int32
		return ret
	}
	return *o.ShopId
}

// GetShopIdOk returns a tuple with the ShopId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetShopIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ShopId) {
		return nil, false
	}
	return o.ShopId, true
}

// HasShopId returns a boolean if a field has been set.
func (o *Feedback) HasShopId() bool {
	if o != nil && !IsNil(o.ShopId) {
		return true
	}

	return false
}

// SetShopId gets a reference to the given int32 and assigns it to the ShopId field.
func (o *Feedback) SetShopId(v int32) {
	o.ShopId = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Feedback) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Feedback) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Feedback) SetMessage(v string) {
	o.Message = &v
}

// GetReply returns the Reply field value if set, zero value otherwise.
func (o *Feedback) GetReply() string {
	if o == nil || IsNil(o.Reply) {
		var ret string
		return ret
	}
	return *o.Reply
}

// GetReplyOk returns a tuple with the Reply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetReplyOk() (*string, bool) {
	if o == nil || IsNil(o.Reply) {
		return nil, false
	}
	return o.Reply, true
}

// HasReply returns a boolean if a field has been set.
func (o *Feedback) HasReply() bool {
	if o != nil && !IsNil(o.Reply) {
		return true
	}

	return false
}

// SetReply gets a reference to the given string and assigns it to the Reply field.
func (o *Feedback) SetReply(v string) {
	o.Reply = &v
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *Feedback) GetScore() int32 {
	if o == nil || IsNil(o.Score) {
		var ret int32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *Feedback) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given int32 and assigns it to the Score field.
func (o *Feedback) SetScore(v int32) {
	o.Score = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Feedback) GetCreatedAt() int32 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int32
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetCreatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Feedback) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int32 and assigns it to the CreatedAt field.
func (o *Feedback) SetCreatedAt(v int32) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Feedback) GetUpdatedAt() int32 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int32
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetUpdatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Feedback) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int32 and assigns it to the UpdatedAt field.
func (o *Feedback) SetUpdatedAt(v int32) {
	o.UpdatedAt = &v
}

// GetProductTitle returns the ProductTitle field value if set, zero value otherwise.
func (o *Feedback) GetProductTitle() string {
	if o == nil || IsNil(o.ProductTitle) {
		var ret string
		return ret
	}
	return *o.ProductTitle
}

// GetProductTitleOk returns a tuple with the ProductTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetProductTitleOk() (*string, bool) {
	if o == nil || IsNil(o.ProductTitle) {
		return nil, false
	}
	return o.ProductTitle, true
}

// HasProductTitle returns a boolean if a field has been set.
func (o *Feedback) HasProductTitle() bool {
	if o != nil && !IsNil(o.ProductTitle) {
		return true
	}

	return false
}

// SetProductTitle gets a reference to the given string and assigns it to the ProductTitle field.
func (o *Feedback) SetProductTitle(v string) {
	o.ProductTitle = &v
}

// GetProductImageName returns the ProductImageName field value if set, zero value otherwise.
func (o *Feedback) GetProductImageName() string {
	if o == nil || IsNil(o.ProductImageName) {
		var ret string
		return ret
	}
	return *o.ProductImageName
}

// GetProductImageNameOk returns a tuple with the ProductImageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetProductImageNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProductImageName) {
		return nil, false
	}
	return o.ProductImageName, true
}

// HasProductImageName returns a boolean if a field has been set.
func (o *Feedback) HasProductImageName() bool {
	if o != nil && !IsNil(o.ProductImageName) {
		return true
	}

	return false
}

// SetProductImageName gets a reference to the given string and assigns it to the ProductImageName field.
func (o *Feedback) SetProductImageName(v string) {
	o.ProductImageName = &v
}

// GetProductImageStorage returns the ProductImageStorage field value if set, zero value otherwise.
func (o *Feedback) GetProductImageStorage() string {
	if o == nil || IsNil(o.ProductImageStorage) {
		var ret string
		return ret
	}
	return *o.ProductImageStorage
}

// GetProductImageStorageOk returns a tuple with the ProductImageStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetProductImageStorageOk() (*string, bool) {
	if o == nil || IsNil(o.ProductImageStorage) {
		return nil, false
	}
	return o.ProductImageStorage, true
}

// HasProductImageStorage returns a boolean if a field has been set.
func (o *Feedback) HasProductImageStorage() bool {
	if o != nil && !IsNil(o.ProductImageStorage) {
		return true
	}

	return false
}

// SetProductImageStorage gets a reference to the given string and assigns it to the ProductImageStorage field.
func (o *Feedback) SetProductImageStorage(v string) {
	o.ProductImageStorage = &v
}

// GetCloudflareImageId returns the CloudflareImageId field value if set, zero value otherwise.
func (o *Feedback) GetCloudflareImageId() string {
	if o == nil || IsNil(o.CloudflareImageId) {
		var ret string
		return ret
	}
	return *o.CloudflareImageId
}

// GetCloudflareImageIdOk returns a tuple with the CloudflareImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetCloudflareImageIdOk() (*string, bool) {
	if o == nil || IsNil(o.CloudflareImageId) {
		return nil, false
	}
	return o.CloudflareImageId, true
}

// HasCloudflareImageId returns a boolean if a field has been set.
func (o *Feedback) HasCloudflareImageId() bool {
	if o != nil && !IsNil(o.CloudflareImageId) {
		return true
	}

	return false
}

// SetCloudflareImageId gets a reference to the given string and assigns it to the CloudflareImageId field.
func (o *Feedback) SetCloudflareImageId(v string) {
	o.CloudflareImageId = &v
}

// GetInvoice returns the Invoice field value if set, zero value otherwise.
func (o *Feedback) GetInvoice() MiniInvoice {
	if o == nil || IsNil(o.Invoice) {
		var ret MiniInvoice
		return ret
	}
	return *o.Invoice
}

// GetInvoiceOk returns a tuple with the Invoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetInvoiceOk() (*MiniInvoice, bool) {
	if o == nil || IsNil(o.Invoice) {
		return nil, false
	}
	return o.Invoice, true
}

// HasInvoice returns a boolean if a field has been set.
func (o *Feedback) HasInvoice() bool {
	if o != nil && !IsNil(o.Invoice) {
		return true
	}

	return false
}

// SetInvoice gets a reference to the given MiniInvoice and assigns it to the Invoice field.
func (o *Feedback) SetInvoice(v MiniInvoice) {
	o.Invoice = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *Feedback) GetProduct() FeedbackProduct {
	if o == nil || IsNil(o.Product) {
		var ret FeedbackProduct
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetProductOk() (*FeedbackProduct, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *Feedback) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given FeedbackProduct and assigns it to the Product field.
func (o *Feedback) SetProduct(v FeedbackProduct) {
	o.Product = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *Feedback) GetUpdatedBy() int32 {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret int32
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Feedback) GetUpdatedByOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *Feedback) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given int32 and assigns it to the UpdatedBy field.
func (o *Feedback) SetUpdatedBy(v int32) {
	o.UpdatedBy = &v
}

func (o Feedback) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Feedback) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uniqid) {
		toSerialize["uniqid"] = o.Uniqid
	}
	if !IsNil(o.ProductId) {
		toSerialize["product_id"] = o.ProductId
	}
	if !IsNil(o.InvoiceId) {
		toSerialize["invoice_id"] = o.InvoiceId
	}
	if !IsNil(o.Blocked) {
		toSerialize["blocked"] = o.Blocked
	}
	if !IsNil(o.Appealed) {
		toSerialize["appealed"] = o.Appealed
	}
	if !IsNil(o.ShopId) {
		toSerialize["shop_id"] = o.ShopId
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Reply) {
		toSerialize["reply"] = o.Reply
	}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.ProductTitle) {
		toSerialize["product_title"] = o.ProductTitle
	}
	if !IsNil(o.ProductImageName) {
		toSerialize["product_image_name"] = o.ProductImageName
	}
	if !IsNil(o.ProductImageStorage) {
		toSerialize["product_image_storage"] = o.ProductImageStorage
	}
	if !IsNil(o.CloudflareImageId) {
		toSerialize["cloudflare_image_id"] = o.CloudflareImageId
	}
	if !IsNil(o.Invoice) {
		toSerialize["invoice"] = o.Invoice
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updated_by"] = o.UpdatedBy
	}
	return toSerialize, nil
}

type NullableFeedback struct {
	value *Feedback
	isSet bool
}

func (v NullableFeedback) Get() *Feedback {
	return v.value
}

func (v *NullableFeedback) Set(val *Feedback) {
	v.value = val
	v.isSet = true
}

func (v NullableFeedback) IsSet() bool {
	return v.isSet
}

func (v *NullableFeedback) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeedback(val *Feedback) *NullableFeedback {
	return &NullableFeedback{value: val, isSet: true}
}

func (v NullableFeedback) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeedback) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


