/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sellix

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentResponseWhiteLabelData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentResponseWhiteLabelData{}

// PaymentResponseWhiteLabelData struct for PaymentResponseWhiteLabelData
type PaymentResponseWhiteLabelData struct {
	Invoice Invoice `json:"invoice"`
}

type _PaymentResponseWhiteLabelData PaymentResponseWhiteLabelData

// NewPaymentResponseWhiteLabelData instantiates a new PaymentResponseWhiteLabelData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentResponseWhiteLabelData(invoice Invoice) *PaymentResponseWhiteLabelData {
	this := PaymentResponseWhiteLabelData{}
	this.Invoice = invoice
	return &this
}

// NewPaymentResponseWhiteLabelDataWithDefaults instantiates a new PaymentResponseWhiteLabelData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentResponseWhiteLabelDataWithDefaults() *PaymentResponseWhiteLabelData {
	this := PaymentResponseWhiteLabelData{}
	return &this
}

// GetInvoice returns the Invoice field value
func (o *PaymentResponseWhiteLabelData) GetInvoice() Invoice {
	if o == nil {
		var ret Invoice
		return ret
	}

	return o.Invoice
}

// GetInvoiceOk returns a tuple with the Invoice field value
// and a boolean to check if the value has been set.
func (o *PaymentResponseWhiteLabelData) GetInvoiceOk() (*Invoice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invoice, true
}

// SetInvoice sets field value
func (o *PaymentResponseWhiteLabelData) SetInvoice(v Invoice) {
	o.Invoice = v
}

func (o PaymentResponseWhiteLabelData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentResponseWhiteLabelData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invoice"] = o.Invoice
	return toSerialize, nil
}

func (o *PaymentResponseWhiteLabelData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invoice",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentResponseWhiteLabelData := _PaymentResponseWhiteLabelData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentResponseWhiteLabelData)

	if err != nil {
		return err
	}

	*o = PaymentResponseWhiteLabelData(varPaymentResponseWhiteLabelData)

	return err
}

type NullablePaymentResponseWhiteLabelData struct {
	value *PaymentResponseWhiteLabelData
	isSet bool
}

func (v NullablePaymentResponseWhiteLabelData) Get() *PaymentResponseWhiteLabelData {
	return v.value
}

func (v *NullablePaymentResponseWhiteLabelData) Set(val *PaymentResponseWhiteLabelData) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentResponseWhiteLabelData) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentResponseWhiteLabelData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentResponseWhiteLabelData(val *PaymentResponseWhiteLabelData) *NullablePaymentResponseWhiteLabelData {
	return &NullablePaymentResponseWhiteLabelData{value: val, isSet: true}
}

func (v NullablePaymentResponseWhiteLabelData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentResponseWhiteLabelData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


