/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreatePaymentRequestFraudShield type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePaymentRequestFraudShield{}

// CreatePaymentRequestFraudShield Customer details to be used by our fraud shield in order to score potential fraud attempts.
type CreatePaymentRequestFraudShield struct {
	// Customer IP.
	Ip *string `json:"ip,omitempty"`
	// Customer user agent.
	UserAgent *string `json:"user_agent,omitempty"`
	// Customer user language.
	UserLanguage *string `json:"user_language,omitempty"`
	// The maximum fraud score a customer can have for the payment to be processed. Between 0 and 100, if set to 100 all fraud checks will be skipped and the invoice will be created.
	MaximumFraudScore *int32 `json:"maximum_fraud_score,omitempty"`
}

// NewCreatePaymentRequestFraudShield instantiates a new CreatePaymentRequestFraudShield object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePaymentRequestFraudShield() *CreatePaymentRequestFraudShield {
	this := CreatePaymentRequestFraudShield{}
	return &this
}

// NewCreatePaymentRequestFraudShieldWithDefaults instantiates a new CreatePaymentRequestFraudShield object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePaymentRequestFraudShieldWithDefaults() *CreatePaymentRequestFraudShield {
	this := CreatePaymentRequestFraudShield{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *CreatePaymentRequestFraudShield) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentRequestFraudShield) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *CreatePaymentRequestFraudShield) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *CreatePaymentRequestFraudShield) SetIp(v string) {
	o.Ip = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *CreatePaymentRequestFraudShield) GetUserAgent() string {
	if o == nil || IsNil(o.UserAgent) {
		var ret string
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentRequestFraudShield) GetUserAgentOk() (*string, bool) {
	if o == nil || IsNil(o.UserAgent) {
		return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *CreatePaymentRequestFraudShield) HasUserAgent() bool {
	if o != nil && !IsNil(o.UserAgent) {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given string and assigns it to the UserAgent field.
func (o *CreatePaymentRequestFraudShield) SetUserAgent(v string) {
	o.UserAgent = &v
}

// GetUserLanguage returns the UserLanguage field value if set, zero value otherwise.
func (o *CreatePaymentRequestFraudShield) GetUserLanguage() string {
	if o == nil || IsNil(o.UserLanguage) {
		var ret string
		return ret
	}
	return *o.UserLanguage
}

// GetUserLanguageOk returns a tuple with the UserLanguage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentRequestFraudShield) GetUserLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.UserLanguage) {
		return nil, false
	}
	return o.UserLanguage, true
}

// HasUserLanguage returns a boolean if a field has been set.
func (o *CreatePaymentRequestFraudShield) HasUserLanguage() bool {
	if o != nil && !IsNil(o.UserLanguage) {
		return true
	}

	return false
}

// SetUserLanguage gets a reference to the given string and assigns it to the UserLanguage field.
func (o *CreatePaymentRequestFraudShield) SetUserLanguage(v string) {
	o.UserLanguage = &v
}

// GetMaximumFraudScore returns the MaximumFraudScore field value if set, zero value otherwise.
func (o *CreatePaymentRequestFraudShield) GetMaximumFraudScore() int32 {
	if o == nil || IsNil(o.MaximumFraudScore) {
		var ret int32
		return ret
	}
	return *o.MaximumFraudScore
}

// GetMaximumFraudScoreOk returns a tuple with the MaximumFraudScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePaymentRequestFraudShield) GetMaximumFraudScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.MaximumFraudScore) {
		return nil, false
	}
	return o.MaximumFraudScore, true
}

// HasMaximumFraudScore returns a boolean if a field has been set.
func (o *CreatePaymentRequestFraudShield) HasMaximumFraudScore() bool {
	if o != nil && !IsNil(o.MaximumFraudScore) {
		return true
	}

	return false
}

// SetMaximumFraudScore gets a reference to the given int32 and assigns it to the MaximumFraudScore field.
func (o *CreatePaymentRequestFraudShield) SetMaximumFraudScore(v int32) {
	o.MaximumFraudScore = &v
}

func (o CreatePaymentRequestFraudShield) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePaymentRequestFraudShield) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.UserAgent) {
		toSerialize["user_agent"] = o.UserAgent
	}
	if !IsNil(o.UserLanguage) {
		toSerialize["user_language"] = o.UserLanguage
	}
	if !IsNil(o.MaximumFraudScore) {
		toSerialize["maximum_fraud_score"] = o.MaximumFraudScore
	}
	return toSerialize, nil
}

type NullableCreatePaymentRequestFraudShield struct {
	value *CreatePaymentRequestFraudShield
	isSet bool
}

func (v NullableCreatePaymentRequestFraudShield) Get() *CreatePaymentRequestFraudShield {
	return v.value
}

func (v *NullableCreatePaymentRequestFraudShield) Set(val *CreatePaymentRequestFraudShield) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePaymentRequestFraudShield) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePaymentRequestFraudShield) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePaymentRequestFraudShield(val *CreatePaymentRequestFraudShield) *NullableCreatePaymentRequestFraudShield {
	return &NullableCreatePaymentRequestFraudShield{value: val, isSet: true}
}

func (v NullableCreatePaymentRequestFraudShield) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePaymentRequestFraudShield) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


