/*
Sellix Developers API

Sellix public API for developers to access merchant resources

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCustomerPaymentMethods200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCustomerPaymentMethods200ResponseData{}

// GetCustomerPaymentMethods200ResponseData struct for GetCustomerPaymentMethods200ResponseData
type GetCustomerPaymentMethods200ResponseData struct {
	PaymentMethods []PaymentMethod `json:"payment_methods,omitempty"`
}

// NewGetCustomerPaymentMethods200ResponseData instantiates a new GetCustomerPaymentMethods200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCustomerPaymentMethods200ResponseData() *GetCustomerPaymentMethods200ResponseData {
	this := GetCustomerPaymentMethods200ResponseData{}
	return &this
}

// NewGetCustomerPaymentMethods200ResponseDataWithDefaults instantiates a new GetCustomerPaymentMethods200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCustomerPaymentMethods200ResponseDataWithDefaults() *GetCustomerPaymentMethods200ResponseData {
	this := GetCustomerPaymentMethods200ResponseData{}
	return &this
}

// GetPaymentMethods returns the PaymentMethods field value if set, zero value otherwise.
func (o *GetCustomerPaymentMethods200ResponseData) GetPaymentMethods() []PaymentMethod {
	if o == nil || IsNil(o.PaymentMethods) {
		var ret []PaymentMethod
		return ret
	}
	return o.PaymentMethods
}

// GetPaymentMethodsOk returns a tuple with the PaymentMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCustomerPaymentMethods200ResponseData) GetPaymentMethodsOk() ([]PaymentMethod, bool) {
	if o == nil || IsNil(o.PaymentMethods) {
		return nil, false
	}
	return o.PaymentMethods, true
}

// HasPaymentMethods returns a boolean if a field has been set.
func (o *GetCustomerPaymentMethods200ResponseData) HasPaymentMethods() bool {
	if o != nil && !IsNil(o.PaymentMethods) {
		return true
	}

	return false
}

// SetPaymentMethods gets a reference to the given []PaymentMethod and assigns it to the PaymentMethods field.
func (o *GetCustomerPaymentMethods200ResponseData) SetPaymentMethods(v []PaymentMethod) {
	o.PaymentMethods = v
}

func (o GetCustomerPaymentMethods200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCustomerPaymentMethods200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PaymentMethods) {
		toSerialize["payment_methods"] = o.PaymentMethods
	}
	return toSerialize, nil
}

type NullableGetCustomerPaymentMethods200ResponseData struct {
	value *GetCustomerPaymentMethods200ResponseData
	isSet bool
}

func (v NullableGetCustomerPaymentMethods200ResponseData) Get() *GetCustomerPaymentMethods200ResponseData {
	return v.value
}

func (v *NullableGetCustomerPaymentMethods200ResponseData) Set(val *GetCustomerPaymentMethods200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCustomerPaymentMethods200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCustomerPaymentMethods200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCustomerPaymentMethods200ResponseData(val *GetCustomerPaymentMethods200ResponseData) *NullableGetCustomerPaymentMethods200ResponseData {
	return &NullableGetCustomerPaymentMethods200ResponseData{value: val, isSet: true}
}

func (v NullableGetCustomerPaymentMethods200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCustomerPaymentMethods200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


